XRayMonitor:
  LogEngine: logblock
  Worlds:
    survival: Default
    survival_neither: Disabled
    survival_the_end: Disabled
    adventure: Default
  DefaultRates:
    DIAMOND_ORE:
      warn: 3.2
      confirmed: 3.8
      xlevel_weight: 20
    EMERALD_ORE:
      warn: 0.7
      confirmed: 1.2
      xlevel_weight: 25
    GOLD_ORE:
      warn: 8.0
      confirmed: 10.0
      xlevel_weight: 10
    IRON_ORE:
      warn: 40.0
      confirmed: 70.0
      xlevel_weight: 1
    LAPIS_ORE:
      warn: 3.2
      confirmed: 3.8
      xlevel_weight: 8
    REDSTONE_ORE:
      warn: 25.0
      confirmed: 50.0
      xlevel_weight: 8
    SPAWNER:
      warn: 1.5
      confirmed: 3.0
      xlevel_weight: 15
  StoneBlocks:
    - STONE
    - DIORITE
    - ANDESITE
    - GRANITE
  OreBlocks:
    DIAMOND_ORE: true
    EMERALD_ORE: true
    GOLD_ORE: true
    IRON_ORE: false
    LAPIS_ORE: false
    REDSTONE_ORE: false
    MOSSY_COBBLESTONE: false
    SPAWNER: true
  NotifyConsole: false
